title: Chatri CHANSUK # your name (or website title) here
logo: "/images/avatar.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Etudiant en Master 2 en Data Science, je possède des compétences avancées en analyse de données, machine learning et visualisation de données. 
  Je suis passionné par la résolution de problèmes complexes en utilisant des techniques de pointe en data science.
  <br><br>
  Disponible pour un un stage en data science d'une durée de 4/5 mois à partir de Mai 2023
  <br><br>
  <a href="https://www.linkedin.com/in/chatri-chansuk/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
